llvm/llvm-test-suite

External/HeCBench/CMakeLists.txt
External/HeCBench/README

Added the HeCBench Collection.
HeCBench is a collection of benchmarks written with CUDA, HIP, SYCL/DPC++, and OpenMP-4.5 target offloading. For more information see https://github.com/zjin-lcf/HeCBench.
Using the benchmarks written with OpenMP. Only added a handful of benchmarks were added. Work needs to be done to add more benchmarks into the WhiteList.

[TestSuite][OpenMP] Add HeCBench external project for OpenMP

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/EnabledFilesHLFIR.cmake
Fortran/gfortran/torture/execute/DisabledFiles.cmake
Fortran/gfortran/torture/execute/DisabledFilesHLFIR.cmake

Disable two tests that fail when optimizations are enabled, but pass otherwise. Comments have been added in the two DisabledFiles.cmake files describing why the tests were disabled.
These failures were reproduced by @kiranchandramohan  and @cabreraam on Slack.

[test-suite][Fortran] Fix failing tests from gfortran test suite

---

Fortran/gfortran/CMakeLists.txt

My use case is to limit long-running compilation (stuck, infinite loop). It should be useful for tools like ccache too.

[Fortran][gfortran] respect CMAKE_Fortran_COMPILER_LAUNCHER

---

Fortran/gfortran/regression/DisabledFiles.cmake

is_contiguous_1.f90 explicitly says that it is testing for an IS_CONTIGUOUS result with zero sized array that goes against what is required in the standard. Zero and one sized arrays are contiguous, even when obtained with triplet strides that are not ones.
Flang behavior will be standard conformant and align with ifort and nagfor after https://github.com/llvm/llvm-project/pull/68869.
So this test needs to be disabled.
Move is_contiguous_3.f90 under the same comment since it is failing for the same valid reason (except IS_CONTIGUOUS was folded at compile time and therefore already correct with flang).

[Fortran][gfortran] Disable is_contiguous_1 that is nonconformant

---

External/SPEC/CFP2006/453.povray/CMakeLists.txt

453.povray ref test failed when running SPEC CPU2006 1.1 on a LoongArch host with clang-18.
This patch disables fp-contract to keep the generated SPEC-benchmark.tga same with the reference.
For more information about the change of the default behavior of fp-contract, see:
https://bugs.llvm.org/show_bug.cgi?id=51346

Fix 453.povray test on LoongArch

---

MultiSource/Benchmarks/DOE-ProxyApps-C++/CLAMR/input.cpp

- The variable "progCL" is a l-value and never get used, but it will cause SEGV when argv (binary file path) is longer than its pre-defined length.

[CLAMR] remove unused codes

---

Fortran/gfortran/regression/DisabledFiles.cmake

Flang now allows a superfluous CONTIGUOUS attribute to appear on objects that are simply contiguous or scalar.  Disable three gfortran tests that check for errors in these cases.

[flang][test] Disable three tests

---

Fortran/UnitTests/finalization/README.md

Fix typos in `Fortran/UnitTests/finalization/README.md`

doc(README.md): fix typos

---

Fortran/gfortran/regression/DisabledFiles.cmake

Patch required before enabling HLFIR by default:
https://github.com/llvm/llvm-project/pull/72090
Three batches of tests must be disabled.
1. test using non constant length character elemental fuctions
2. test using pointer assignments inside FORALL
3. "error" test that previously "wrongly" passed (did not throw runtime errors as they should have)
For the first two batches, lowering without HFLIR handled a few cases , but did not fully handle the features correctly. With HLFIR, it was decided to make all cases TODO until the feature are handled correctly. They are not very common, hence I think the "feature regression" is acceptable for now compared to what HLFIR brings.
For, the last batch, the test suite is not set to run error checking tests (verifying a runtime error that is expected …

[Fortran] Disabling error tests and tests not yet working with HLFIR

---

Fortran/gfortran/regression/DisabledFiles.cmake

These tests are looking for a semantic error that flang is not emitting but they used to pass because a TODO for procedure pointers was emitted in lowering. Lowering implemented procedure pointers, so these test now fail. I opened an issue against semantics, but I want to comment out these tests so that we can still land the lowering implementation of procedure pointers that is correct (the lowering change was reverted for now).
See https://github.com/llvm/llvm-project/issues/73215

[Fortran] Comment out tests with missing semantic checks

---

SingleSource/UnitTests/Vectorizer/CMakeLists.txt
SingleSource/UnitTests/Vectorizer/VPlanNativePath/CMakeLists.txt
SingleSource/UnitTests/Vectorizer/VPlanNativePath/outer-loop-vect.cpp
SingleSource/UnitTests/Vectorizer/VPlanNativePath/outer-loop-vect.reference_output

This patch adds unit tests for LLVM's VPlan-native path, as requested in https://reviews.llvm.org/D157484.
The new Vectorizer/VPlanNativePath subdirectory is only enabled if the compiler is clang. For all source files in that directory, the flags "-mllvm -enable-vplan-native-path" are added.
Four different scenarios are tested for outer-loop vectorization:
- Matrix multiplication, where the second of three loops is vectorized.
- A test where the vectorized loop has an auxiliary induction variable.
- A test for indirect and strided memory accesses.
- A nesting of three loops where the outer-most one is vectorized.

[SingleSource/Vectorizer] Add unit tests for the vplan-native path.

---

Fortran/gfortran/regression/DisabledFiles.cmake

Remove many tests from Fortran/gfortran/regression/DisabledFiles.cmake that now pass.  Move others around from more general classifications to groups with specific diagnoses like "unimplemented feature" or "bad test".

[flang] Scrub lists of failing tests in DisabledFiles.cmake

---

SingleSource/UnitTests/Float/check-helper.h
SingleSource/UnitTests/Float/classify-f32.h
SingleSource/UnitTests/Float/classify-f64.h
SingleSource/UnitTests/Float/classify-f80.h
SingleSource/UnitTests/Float/classify-ldouble.h
SingleSource/UnitTests/Float/classify.c
SingleSource/UnitTests/Float/fformat.h
SingleSource/UnitTests/Float/gen_isfpclass_funcs.h
SingleSource/UnitTests/Float/test_isfpclass.h

This change adds tests for functions 'iszero', 'issubnornal' and 'issignaling'. It also adds tests for Intel fp80 type and some other small enhancements.
Migrated from: https://reviews.llvm.org/D112933

Tests for additional builtin classification functions

---

MultiSource/Applications/ClamAV/CMakeLists.txt

zlib failed to build with a recent compiler extension (https://github.com/llvm/llvm-project/pull/74676). Workaround the build failure by disabling the extension for now.

Workaround build failure in ClamAV with zlib

---

Fortran/gfortran/CMakeLists.txt
tools/CMakeLists.txt
tools/not.cpp

Add a tool very similar to LLVM's not utility which inverts the return code of a command. The major difference is that the utility is not dependent on LLVM's libraries and performs less error checking than LLVM's not. It does support the
--crash option when the command is expected to crash.
There is a need for something similar to the `not` utility in the gfortran test suite where some tests are [expected to crash](https://github.com/llvm/llvm-test-suite/pull/57#discussion_r1420934396). However, we cannot rely on the utility being available since the LLVM build directory may not be available when running the test suite. Unless LLVM was built with `-DLLVM_INSTALL_UTILS=On`, the utilities will not be available even if clang/flang are present.
In keeping with some of the other tools in the …

[Fortran/gfortran] Add a simple not tool to the test suite

---

External/HeCBench/CMakeLists.txt

finishing the conversion to work with new system of declaring which list  to use

Fixing External/HecBench

---

SingleSource/Regression/C/gcc-c-torture/execute/CMakeLists.txt

[gcc-c-torture] use -fwrapv for 950704-1.c (signed overflow)

---

Fortran/gfortran/regression/DisabledFiles.cmake

Fixes have gone into llvm-project/main that fix several tests in Fortran/gfortran/regression/DisabledFiles.cmake; delete them from this file.  Other tests were noticed to be working, and were also deleted.  Some others were moved from generically described blocks of tests into blocks with more specific descriptions.

[flang] Remove more working/fixed tests, classify others

---

cmake/modules/Host.cmake
tools/timeit.c

This patch implements timeit timing tool found at tools/timeit.c for Windows.
It is required for compile time and run time calculations by the llvm-testsuite.
At this moment llvm testsuite tests can not be compiled with clang-cl MSVC combination
however we have also made required modifications to the cmake files to enable building
timeit on windows with clang-cl/cl.
In developer console with MSVC following command can be used to successfully build this code:
set CC=c:\\work\\llvm-dev\\build\\bin\\clang-cl.exe
set CXX=c:\\work\\llvm-dev\\build\\bin\\clang-cl.exe
cmake -G Ninja -DTEST_SUITE_SUBDIRS= ..\\llvm-test-suite
Phabricator Review: https://reviews.llvm.org/D153263

Port tools/timeit to windows (AArch64, x64)

---

tools/CMakeLists.txt
tools/not.cpp

This addresses issue #77137 (std::system is not available on iOS). The implementation uses posix_spawn on iOS but std::system elsewhere.
This has only been tested on Linux on X86 and an older AArch64. 
@jroelofs, could you try this on an iOS and let me know if it works there?

[tools] Fix not utility to work on iOS

---

Fortran/SNAP/src/CMakeLists.txt
Fortran/UnitTests/fcvs21_f95/CMakeLists.txt

This patch makes minor changes to ignore windows line endings when Fortran tests are run on windows platform.

Fix Fortran tests for Windows platform

---

CMakeLists.txt
cmake/modules/CopyDir.cmake
cmake/modules/TestSuite.cmake

This patch makes some minor adjustments to top level CMakeLists.txt and CopyDir, Testsuite modules to allow testsuite build on windows.

Fix CMake modules to allow build on windows

---

CMakeLists.txt
cmake/modules/HandleCompilerRT.cmake

This patch adds find compiler-rt libs function imported from llvm-project/cmake/modules to testsuite repository. Some tests require to link compiler-rt builtins library on windows and this function helps locate the library path from install dir.

Add find compiler-rt libs cmake module for windows

---

litsupport/modules/timeit.py
litsupport/shellcommand.py
litsupport/testfile.py

This patch makes changes required in litsupport/* to support running llvm testsuite on windows platform.

litsupport changes for windows support

---

Fortran/gfortran/regression/DisabledFiles.cmake

build and pass all three tests on Linux, will test it on Windows later today

[flang]enable execute_command_line tests

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/c-interop/DisabledFiles.cmake

Recent changes to generic interface analysis have reduced a previous hard error message to an optional warning.  These tests must be run with -pedantic -Werror to cause compilation to fail.  Until I can figure out how to make that happen, disable those tests so that build bots don't fail.

[flang] Disable some tests whose errors are now warnings

---

Fortran/gfortran/regression/DisabledFiles.cmake

char_length_2{0,1}.f90 were fixed in
https://github.com/llvm/llvm-project/pull/80412.
Now that these successfully compile I thought I might as well re-categorise the other tests in the same group too.

[Fortran] mark rhs LEN parameter tests as implemented

---

Fortran/UnitTests/fcvs21_f95/CMakeLists.txt

Now that we're not using libpgmath, these tests pass on AArch64.
They may work on Windows now but I don't have a build setup to check yet, and none of the builders run the test suite yet. If/when I can confirm, I'll come back and remove the Windows check too.

[Fortran] Enable tests that failed when using libpgmath on AArch64 Linux

---

Fortran/gfortran/CMakeLists.txt

Add more flags that are used in the gfortran test suite but are not supported by flang to the list of blacklisted flags.
-----------------
This should not affect the tests as they are run currently, but will be necessary when the static test configuration are used.

[Fortran/gfortran][NFC] Update erroring FFLAGS list

---

utils/compare.py

As of Python 3.12 there's now a syntax warning for invalid escape sequences:
./utils/compare.py:195: SyntaxWarning: invalid escape sequence '\g'
This fixes it by using a raw string literal, as recommended here:
https://docs.python.org/3/library/re.html

utils/compare.py: Fix syntax warning on python 3.12

---

Fortran/gfortran/CMakeLists.txt
Fortran/gfortran/regression/CMakeLists.txt
Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/analyzer/CMakeLists.txt
Fortran/gfortran/regression/asan/CMakeLists.txt
Fortran/gfortran/regression/c-interop/CMakeLists.txt
Fortran/gfortran/regression/coarray/CMakeLists.txt
Fortran/gfortran/regression/debug/CMakeLists.txt
Fortran/gfortran/regression/g77/CMakeLists.txt
Fortran/gfortran/regression/goacc-gomp/CMakeLists.txt
Fortran/gfortran/regression/goacc/CMakeLists.txt
Fortran/gfortran/regression/goacc/DisabledFiles.cmake
Fortran/gfortran/regression/gomp/CMakeLists.txt
Fortran/gfortran/regression/gomp/appendix-a/CMakeLists.txt
Fortran/gfortran/regression/ieee/CMakeLists.txt
Fortran/gfortran/regression/lto/CMakeLists.txt
Fortran/gfortran/regression/ubsan/CMakeLists.txt
Fortran/gfortran/regression/vect/CMakeLists.txt
Fortran/gfortran/torture/compile/CMakeLists.txt
Fortran/gfortran/torture/execute/CMakeLists.txt

Switches the existing build system to use the static test configuration files that were added to the repository in previous commits. The previous method is jettisoned in its entirety. Several tests have been disabled in the process. Some of these are because of limitations in the build system which will be fixed in the future. Others ought to have failed earlier but did not because they were not being built with the correct compiler flags. Now that they are built correctly, they expose limitations of flag which will need to be fixed.
-----------
[edit] Notes for reviewers:
- I may have disabled more tests than strictly necessary to have the default configuration pass. The next patch in this sequence will enable tests that are currently disabled and do pass, so those should get removed …

[Fortran/gfortran] Switch to using the static test configuration files

---

Fortran/gfortran/regression/tests.cmake

It used to fail due to the missing runtime support, but this
was not considered a failure.
It fails due to https://github.com/llvm/llvm-project/issues/84088 now.
This should resolve the buildbot failure:
https://lab.llvm.org/buildbot/#/builders/184/builds/10735

[flang] Disable pr36006-2 on aarch64.

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/tests.cmake

It used to fail due to the missing runtime support, but this
was not considered a failure.
It fails due to llvm/llvm-project#84088 now.
This should resolve the buildbot failure:
https://lab.llvm.org/buildbot/#/builders/184/builds/10735
This also reverts #104.

[flang] Disable pr36006-2.

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/analyzer/DisabledFiles.cmake
Fortran/gfortran/regression/asan/DisabledFiles.cmake
Fortran/gfortran/regression/c-interop/DisabledFiles.cmake
Fortran/gfortran/regression/coarray/DisabledFiles.cmake
Fortran/gfortran/regression/g77/DisabledFiles.cmake
Fortran/gfortran/regression/goacc/DisabledFiles.cmake
Fortran/gfortran/regression/gomp/DisabledFiles.cmake
Fortran/gfortran/regression/gomp/appendix-a/DisabledFiles.cmake
Fortran/gfortran/regression/ieee/DisabledFiles.cmake
Fortran/gfortran/regression/vect/DisabledFiles.cmake
Fortran/gfortran/torture/compile/DisabledFiles.cmake
Fortran/gfortran/torture/execute/DisabledFiles.cmake

These tests now pass. There are some tests that only pass on certain platforms, so they are left disabled.

[Fortran/gfortran] Enable passing tests

---

Fortran/gfortran/regression/DisabledFiles.cmake

This was recently enabled in https://github.com/llvm/llvm-test-suite/pull/102
The CI is failing (https://lab.llvm.org/buildbot/#/builders/176/builds/8940) for this test. I can reproduce this locally. This could be an AArch64 specific issue but I do not have a way to verify this does not occur in other architectures, hence disabling.

[Fortran] Disable internal_dummy_2.f08

---

SingleSource/UnitTests/Vector/LASX/lasx-xvpermi_q.c

After the following PR has been reverted, the immediate argument needs to be modified to keep the test result on LA464 and LA664 consistent: 
https://github.com/llvm/llvm-project/pull/84708

[LoongArch] Update the immediate argument of __lasx_xvpermi_q

---

MultiSource/UnitTests/Float/Makefile

```
2024-04-05 01:59:00: running: "make" "-k" "TARGET_CC=None" "TARGET_CXX=None" "TARGET_LLVMGCC=/Users/nshc-yjlee_m/Library/Developer/LxShield/Xcode151_Test_15.1_1.15.1/bin/clang" "TARGET_LLVMGXX=/Users/nshc-yjlee_m/Library/Developer/LxShield/Xcode151_Test_15.1_1.15.1/bin/clang++" "TARGET_FLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "ENABLE_OPTIMIZED=1" "OPTFLAGS=-Os" "LLI_OPTFLAGS=-O2" "LLC_OPTFLAGS=-O2" "DISABLE_JIT=1" "ENABLE_PARALLEL_REPORT=1" "ENABLE_HASHED_PROGRAM_OUTPUT=1" "USE_REFERENCE_OUTPUT=1" "TEST=simple" "CC_UNDER_TEST_IS_CLANG=1" "CC_UNDER_TEST_TARGET_IS_ARM64=1" "ARCH=AArch64" "-C" "MultiSource/UnitTests/Float/" "-j" "16" "report" "report.simple.csv"
Makefile:9: *** invalid syntax in conditional.  Stop.
```
The error occurred and I fixed it.

[UnitTests/Float] Fix makefile in MultiSource/UnitTests/Float

---

Fortran/gfortran/regression/DisabledFiles.cmake

Fixed by https://github.com/llvm/llvm-project/pull/87496

[Fortran] enable gfortran masklr_2

---

Fortran/gfortran/regression/goacc/DisabledFiles.cmake

https://github.com/llvm/llvm-project/issues/90477
These were also observed to cause non-deterministic out of memory errors.

[Fortran/gfortran] Disable OpenACC tests that cause non-deterministic segfaults

---

External/SPEC/CINT2006/483.xalancbmk/CMakeLists.txt
External/SPEC/CINT2017rate/523.xalancbmk_r/CMakeLists.txt

xalan-c contains a latent error in a template that isn't instantiated, which after https://github.com/llvm/llvm-project/pull/90152 will now fail to build. We can workaround it by setting -fdelayed-template-parsing. See https://github.com/llvm/llvm-project/pull/90152#issuecomment-2089786180

[SPEC] Workaround error with latest clang in 523.xalancbmk_r

---

Fortran/gfortran/regression/DisabledFiles.cmake

Some interoperability checks are being relaxed in an upcoming change to the compiler, and an error has been downgraded to a portability warning.  This will cause these three tests to "fail" due to lack of a fatal error, so I'm disabling them now to prevent build bot failures.
If I knew how to run these tests with "-pedantic -Werror", I would do that instead.

[flang] Disable three error tests

---

MultiSource/Applications/ClamAV/CMakeLists.txt

I found an error when testing on a board that supports RISC-V Vector 1.0:
```shell
cc: error: unrecogized command-line option '-fno-define-target-os-macros'
```
I think the problem is probably caused by the lower version of cc?
```
gcc version 13.2.0
```
But I think we can refer to this commit to solve it.
https://github.com/llvm/llvm-test-suite/commit/9b14a92d585657b87f2ca2b135ba9044685393be
Add a condition that is only enabled on APPLE architecture for `-fno-define-target-os-macros`.

Add a check before using `-fno-define-target-os-macros`

---

litsupport/modules/hash.py

Similar to other platforms already opted out, these platforms strip utility does support the extra options used here.

[AIX][z/OS] Disable strip before hashing

---

Fortran/gfortran/regression/DisabledFiles.cmake

This test expect error at build time for 32 bits target. After  https://github.com/llvm/llvm-project/pull/93230 flang is not failing anymore to compile this test. 
This trigger a buildbot error https://lab.llvm.org/buildbot/#/builders/184/builds/13242

Add string_1.f90 to DisabledFiles.cmake

---

ABI-Testsuite/test/mangling/expressions.xpp
ABI-Testsuite/test/mangling/literals1.xpp

That commit changed the mangling of some existing template parameters. This commit adjusts the tests to the new mangling, but keeps old tests under -fclang-abi-compat=17.

Adjust tests for llvm commit 4b163e343cfa

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c

The FMV test uses FMV feature names (e.g. flagm2) which are not available to -march and therefore arguably should not be available to the target attribute. This change adds a way to specify the string for the target attribute independently from the FMV feature.
This is necessary for https://github.com/llvm/llvm-project/commit/2cf1439 which had to be reverted because it caused this test to fail.

[AArch64] add a target guard to FMV test

---

Fortran/UnitTests/CMakeLists.txt
Fortran/UnitTests/assign-goto/CMakeLists.txt
Fortran/UnitTests/assign-goto/assign-goto.f90
Fortran/UnitTests/assign-goto/lit.local.cfg
Fortran/gfortran/regression/DisabledFiles.cmake

Replace it with our own similar test.
The gfortran/regression/assign_5.f90 writes to a constant value which would cause that test to fail if constants are read-only.
A replacement test assign-goto.f90 is introduced to check that this an assigned goto statement compiles and runs without issue.

Disable non-conforming test

---

CMakeLists.txt
utils/rsync.sh

`TEST_SUITE_REMOTE_CLIENT` can be used to pass additional flags to the remote execution client, such as specifying an alternative SSH configuration file.
For example: `TEST_SUITE_REMOTE_CLIENT="ssh -F path/to/config/file"`.

Allow passing additional flags to the remote execution client

---

Fortran/UnitTests/CMakeLists.txt
Fortran/UnitTests/execute_command_line/CMakeLists.txt
Fortran/UnitTests/execute_command_line/execute_command_line.f90
Fortran/UnitTests/execute_command_line/lit.local.cfg
Fortran/gfortran/regression/DisabledFiles.cmake

`execute_command_line` was updated in https://github.com/llvm/llvm-project/pull/93023 with more `cmdstat` and richer `cmdmsg`, so existing test will fail.

update Fortran tests for execute_command_line

---

Fortran/gfortran/regression/gomp/DisabledFiles.cmake
Fortran/gfortran/regression/gomp/appendix-a/DisabledFiles.cmake

These were found through brute force. I haven't checked which PRs fixed them.

[Fortran] enable gomp tests which now pass

---

Fortran/gfortran/CMakeLists.txt
Fortran/gfortran/regression/DisabledFiles.cmake

All the TODOs and bugs related to CLASS have been implemented/fixed. Enable newly passing tests and move all other failing tests under existing or new categories. None of these failures are bugs, most are different TODOs, unimplemented runtime checks, or cases where flang will behave differently than gfortran on purpose.

[fortran] Update gfortran disabled test list now that CLASS is lowered

---

tools/not.cpp

In https://pubs.opengroup.org/onlinepubs/9699919799/functions/wait.html,
- for `WTERMSIG`, 
"If the value of WIFSIGNALED(stat_val) is non-zero, this macro evaluates to the number of the signal that caused the termination of the child process."
- for `WEXITSTATUS`,
"If the value of WIFEXITED(stat_val) is non-zero, this macro evaluates to the low-order 8 bits of the status argument ..."
We need to check `WIFSIGNALED` and `WIFEXTED` before using the values to update `rercode` and `signal`.   On AIX, if `WIFSIGNALED` is zero, `WTERMSIG` has a non-zero value (`0xffffffff`).

Check the returns of WIFSIGNALED and WIFEXITED

---

tools/not.cpp

Avoid using std::system on Unix systems. Some systems such as Ubuntu return a different error code from calls to std::system. Use posix_spawn to avoid having to special case these. std::system is now only used on Windows.
@jeanPerier identified this as an issue [here](https://github.com/llvm/llvm-test-suite/pull/102#issuecomment-1980674221)
@jroelofs, could you check that this doesn't cause any issues on iOS.

[llvm-test-suite][tools] Fix not utility to avoid std::system

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/c-interop/DisabledFiles.cmake
Fortran/gfortran/regression/ieee/DisabledFiles.cmake
Fortran/gfortran/regression/vect/DisabledFiles.cmake

This is likely to be dependent on [another PR](https://github.com/llvm/llvm-test-suite/pull/142). 
@jeanPerier attempted to enable several of these tests [once before](https://github.com/llvm/llvm-test-suite/pull/109), but there were issues with the `not` utility in the test suite that prevented the tests from being enabled then. The [first PR linked above](https://github.com/llvm/llvm-test-suite/pull/142) should have fixed those, so once that lands, these tests should also work.

[Fortran/gfortran] Enable tests that now pass

---

Fortran/gfortran/regression/DisabledFiles.cmake

Several of the AArch64 buildbots are failing due to an undefined reference to __trampoline_setup when compiling internal_dummy_2.f08. This is probably an issue with the buildbot configuration, but in the interest of getting them bots unstuck, the test is being disabled.

[Fortran/gfortran] Disable test to fix failing buildbots

---

Fortran/gfortran/regression/DisabledFiles.cmake

Fortran/gfortran/regression/gfortran-regression-execute-regression__do_check_1_f90.test
still fails after being re-enabled in #143
https://lab.llvm.org/buildbot/#/builders/143/builds/1198

[Fortran/gfortran] Disable another test to fix failing buildbots

---

Fortran/gfortran/regression/DisabledFiles.cmake

The test Fortran/gfortran/regression/submodule_3.f08 is not expected to compile because it uses basic F'08 features while being compiled by gfortran under -std=f2003.  Flang-new wasn't compiling it either, but that was because it had a bug (also in gfortran) dealing with the inheritance of implicit typing rules in procedure interfaces. That bug is (or shortly will be) fixed, and the test now compiles without error, an unexpected result.  Disable the test.

[flang] Disable submodule_3.f08

---

Fortran/gfortran/regression/DisabledFiles.cmake

The random_init_2.f90 test is flaky and may fail sometimes, even
when no Fortran/Flang changes are made:
- https://lab.llvm.org/buildbot/#/builders/143/builds/1236
- https://lab.llvm.org/buildbot/#/builders/17/builds/2058
Looking at the test source, it seems there is no guarantee that 2
distinct random numbers will never collide. This is made worse by
multiplying them by 1e6 and converting them to integer, which could
make distinct but close enough single-precision floating-point
numbers give the same result and fail the test.

[Fortran/gfortran] Disable flaky test random_init_2.f90

---

Fortran/gfortran/regression/DisabledFiles.cmake

Move some disabled tests to the "unsupported" category since these will never be fixed.
----------------
@lupori, could you check that the inline comment describing the `random_init_2.f90` test is correct.

[Fortran/gfortran][NFC] Recategorize tests

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/pr32601.f03

https://github.com/llvm/llvm-project/pull/107353 will relax the check when -pedantic is not enabled. `-std=f2003` is not supported in flang. Disable the test until we have a way to add flags.

[Fortran] Disable pr32601.f03

---

Fortran/gfortran/regression/DisabledFiles.cmake

Fortran/gfortran/regression/restricted_expression_2.f90 and Fortran/gfortran/regression/restricted_expression_3.f90 are disabled with this patch, as the condition that they test will soon no longer be an error with flang, just a warning. (This is the use of a local variable with proper initialization and the SAVE attribute being used as part of a specification expression.)

[flang] Disable two tests as error is being downgraded

---

Bitcode/Benchmarks/Halide/CMakeLists.txt

We occasionally see spurious llvm-test-suite failures with the following error message:
CMake Error: failed to create symbolic link '/tmp/tmp.x1PxF3OhCA/Bitcode/Benchmarks/Halide/local_laplacian/../images/rgb.bytes': File exists
The reason for this is that two halide tests try to copy a test input to the same location, and create_symlink can fail if these calls race.
Fix this by putting the inputs for the tests into different directories, by not making ".." part of the result directory.

Fix spurious errors in halide tests

---

Fortran/gfortran/regression/DisabledFiles.cmake

I'm shortly adding the ability to allow real-looking input for NAMELIST integer values.  GNU Fortran doesn't allow that, and has a test to check its error detection, so disable that test.

[flang] Disable test that expects error from new extension

---

tools/fpcmp.c

There are occasionally spurious failures in llvm-test-suite, and you end up with a phenomenally unhelpful message like:
tools/fpcmp-target: Comparison failed, textual difference between '0' and '7'
This is good enough if you can inspect the inputs to fpcmp locally, but unhelpful for CI failures.
Improve things by dumping the inputs to fpcmp on a textual comparison failure.

fpcmp: Dump inputs on comparison failure

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

Sha1 has been unified with sha2 in the ACLE spec (https://github.com/ARM-software/acle/pull/347) and soon in the compiler (https://github.com/llvm/llvm-project/pull/108383), therefore I am adjusting the runtime tests for it.

[FMV][AArch64] Unify tests for sha1 and sha2.

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

The inline asm tests all three FEAT_LS64, FEAT_LS64_V and FEAT_LS64_ACCDATA.

[FMV][AArch64] Add tests for feature ls64.

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

Adds tests for f32mm, f64mm, fp16fml, frintts, predres, rcpc3, rng, sve, sve2, sve2-bitperm, sve2-sha3, sve2-sm4, wfxt, sb, sm4, sme-f64f64, sme-i16i64, mops.

[FMV] Improve test coverage for FMV features.

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c

When running try_ssbs2() on hardware which is affected by the "SSBS not fully self-synchronizing" errata, the linux kernel mutes the detection of ssbs2 via hardware caps. As a result the default version ends up running the ssbs2 code which was expected to trap originally.
To work around this UPASS I am passing an additional macro parameter to indicate whether the default version is exempt from diagnostics.
This fixes https://github.com/llvm/llvm-project/issues/109304.

[FMV][AArch64] Fix UPASS when "SSBS not fully self-synchronizing".

---

MicroBenchmarks/LoopVectorization/CMakeLists.txt
MicroBenchmarks/LoopVectorization/EpilogueVectorization.cpp

This microbenchmark attempts to test the impact of epilogue vectorization on loops with varying epilogue lengths and vector widths for loops with and without reductions.

[MicroBenchmarks/LoopVectorization] Add Microbenchmark for Epilogue Vectorization

---

Fortran/gfortran/regression/DisabledFiles.cmake
Fortran/gfortran/regression/c-interop/DisabledFiles.cmake

Fix https://lab.llvm.org/buildbot/#/builders/143/builds/2600
Some tests expecting a semantic error wrongly passed because of the lowering TODO for assumed rank that was enabled by default in https://github.com/llvm/llvm-project/pull/110893.

[Fortran] disbale failing tests after assumed-rank were enabled

---

MicroBenchmarks/libs/benchmark/test/options_test.cc

MicroBenchmarks/libs/benchmark/test/options_test.cc fails to build on Linux/AArch64 with following error:
error: variable 'actual_iterations' set but not used
This patch adds benchmark::DoNotOptimize(actual_iterations); to to function BM_explicit_iteration_count in options_test.cc
-Wall and -Werror were being used to compile and I am surprised that this was not caught by any of the buildbots.
Some versions of clang compile this all fine with -Wall -Werror.

Fix MicroBenchmark build on Linux with clang 18.1.8

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

Depends on https://github.com/llvm/llvm-project/pull/110297

[FMV] Rename feature ssbs2 to ssbs.

---

Fortran/gfortran/regression/DisabledFiles.cmake

An upcoming PR to flang (https://github.com/llvm/llvm-project/pull/112024) will soon allow two gfortran tests to compile and run successfully, which will come as a fatal surprise because they're marked "xfail".

[flang] Disable two xfail tests that will soon not fail

---

SingleSource/UnitTests/Vector/LASX/lasx-xvfmadd_d.c
SingleSource/UnitTests/Vector/LASX/lasx_test_util.h
SingleSource/UnitTests/Vector/LSX/lsx-vfmadd_d.c
SingleSource/UnitTests/Vector/LSX/lsx_test_util.h

Because vector support for constant folding was added in visitFMA, the [x]vfmadd.d instructions was optimized into a constant load, causing a bitwise mismatch for NaN values between the expected and actual results. (The NaN from constant folding differs from the NaN generated by the
instruction.)
This should resolve the buildbot failure:
https://lab.llvm.org/staging/#/builders/20/builds/4041

[LoongArch] Add vector floating-point check function

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

There are no FEAT_MTE2 instructions available at EL0, therefore this test is expected to UPASS on systems which support FEAT_MTE but don't support FEAT_MTE2.
Depends on https://github.com/llvm/llvm-project/pull/112511

[FMV][AArch64] Add runtime test for memtag.

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

Those features have been unified here:
https://github.com/ARM-software/acle/pull/352

[FMV][AArch64] Move test for pmull under aes and add test for sve2-aes.

---

External/SPEC/SpecCPU2017.cmake

Without -DSPEC_MANUAL_CONFIG (or another dummy arch/os flag specified), 500.perlbench_r will fail to build on riscv64-linux-gnu. -DSPEC_LP64 and -DSPEC_LINUX are also already defined via the generic handlers above. I'm not sure if we need to define more flags, but this enough to get things building.

[SPEC] Define arch/os portability flag for riscv64-linux-gnu

---

External/HIP/CMakeLists.txt

since it is unstable and causes spurious random failures

temporarily disable HIP test InOneWeekend

---

tools/CMakeLists.txt
tools/not.cpp
tools/test/CMakeLists.txt
tools/test/abort.c
tools/test/check_env.c
tools/test/ret0.c
tools/test/ret1.c
tools/test/test_not.sh

The not utility did not capture the parent's environment variables on POSIX platforms. This has been fixed.
---------------------------
@jroelofs 
Is this valid on Apple platforms?

[tools] Make not tool respect environment variables

---

cmake/modules/SingleMultiSource.cmake

These Fortran suffixes are aligned with [the `lookupTypeForExtension` function in `clang/lib/Driver/Types.cpp`](https://github.com/llvm/llvm-project/blob/4d6a5fc/clang/lib/Driver/Types.cpp#L299).
We Fujitsu want to contribute the [Fujitsu Compiler Test Suite](https://github.com/fujitsu/compiler-test-suite/) to the LLVM test-suite after it becomes ready and we obtain consensus in the community. It includes `*.f95` and `*.for` tests.
This commit affects tests which use `llvm_singlesource` or `llvm_multisource` in `CMakeLists.txt`. I confirmed this commit does not affect any existing tests in the LLVM test-suite.

[cmake] Support more Fortran filename suffixes

---

Fortran/gfortran/regression/DisabledFiles.cmake

Needed after https://github.com/llvm/llvm-project/pull/118070
Both ifx and nvfortran/classic flang also "fail" this non conformant test.

[fortran] disable non conformant gfortran aliasing_array_result_1 test

---

tools/test/CMakeLists.txt
tools/test/test_not.py
tools/test/test_not.sh

The commit 89fcc5e introduced some tests for the tools in the tools/ subdirectory that are always run, but these tests were not working on Windows due to the executables ending in .exe and one of the tests being written in bash.
This commit fixes those issues by directly using the $<TARGET_FILE> generator expressions to get the executable file names, and rewriting the bash test in python.

Fix tools tests on Windows

---

SingleSource/Regression/C/gcc-c-torture/execute/loop-15.c

In the first iteration, we get `foo(a, a)`, which produces an OOB pointer at `temp`.

[SingleSource][Regressions][C] Fix loop-15.c so it does not trigger UB.

---

SingleSource/Benchmarks/CoyoteBench/huffbench.c

The `--heap` results in an out of bounds pointer index. Fix this by subtracting 1 during indexing instead.

Avoid UB in huffbench

---

Fortran/CMakeLists.txt
Fortran/Readme.txt
Fortran/UnitTests/fcvs21_f95/lit.local.cfg
Fortran/UnitTests/finalization/lit.local.cfg
Fortran/lit.local.cfg

Currently out of the box the Fortran tests fail with flang because the NO_STOP_MESSAGE environment variable needs to be set for them to pass. This environment variable should therefore always be set for the tests so that they can pass out of the box.

Always pass NO_STOP_MESSAGE to Fortran tests

---

Fortran/gfortran/regression/DisabledFiles.cmake

The tests started failing at -O2 after https://github.com/llvm/llvm-project/pull/121544
Flang inlines hlfir.assign with hlfir.expr RHSs after the change,
so the runtime is not called, and it does not make the bounds checks.
Related feature request: https://github.com/orgs/llvm/projects/12?pane=issue&itemId=29048733

[Fortran/gfortran] Disable bounds-check tests.

---

MicroBenchmarks/libs/benchmark/cmake/Modules/FindPFM.cmake

libpfm only contains dynamic library in some of our environments. Since we don't actually static link them, only find dynamic library is enough. This also aligns with LLVM's configuration
https://github.com/llvm/llvm-project/blob/7d5376270ae5807a29597a91d7cf59f967ccf39e/llvm/cmake/modules/FindLibpfm.cmake#L13
Cherry-picked from: https://github.com/google/benchmark/commit/a092f8222c1fa95986efe611abf78daba59d3c59

[Microbench] Sync with google/benchmark to change FindPFM.cmake

---

Fortran/gfortran/regression/ieee/override.yaml
Fortran/gfortran/regression/ieee/tests.cmake
Fortran/gfortran/regression/override.yaml
Fortran/gfortran/regression/tests.cmake

The `real(16)` type is not supported on PPC. This patch is to disable those tests on `ppc64le` and `powerpc`.

[Fortran/gfortran] Disable tests with unsupported real type on ppc64le and powerpc

---

External/HIP/workload/blender/test_blender.sh.in

We see test failures in the buildbot and it seems that (at least one reason) is timeouts.

[HIP] Increase blender timeout

---

Fortran/gfortran/regression/DisabledFiles.cmake

The tests started failing at -O2 after https://github.com/llvm/llvm-project/pull/122821
Flang inlines hlfir.matmul[_transpose] after the change,
so the runtime is not called, and it does not make the bounds checks.
Related feature request: https://github.com/orgs/llvm/projects/12?pane=issue&itemId=29048733

[Fortran/gfortran] Disable bounds-check tests for matmul tests.

---

SingleSource/UnitTests/AArch64/acle-fmv-features.c
SingleSource/UnitTests/AArch64/acle-fmv-features.reference_output

Is depended-on by https://github.com/llvm/llvm-project/pull/124266

[FMV] Remove tests for features predres and ls64.

---

Fortran/gfortran/regression/override.yaml
Fortran/gfortran/regression/tests.cmake

The libm routine, `lround`, gives wrong result. This test is disabled temporarily.

[Fortran/gfortran] Disable test on AIX

---

MultiSource/Benchmarks/MallocBench/cfrac/pops.c

It is undefined behaviour to construct a pointer that is out-of-bounds, not just to use it.
Cherry-pick of commit in mimalloc-bench:
https://github.com/daanx/mimalloc-bench/commit/b517ae367c186be7365d238806b475478637d8f2

Fix UB in pops.c

---

Fortran/gfortran/regression/gomp/DisabledFiles.cmake

This test is expected to fail but now passes. It previously failed because it triggered a not-yet-implemented error, not because it failed for the reasons intended by the test.
The test checks that some openmp library calls are not allowed inside of omp teams. These semantic checks are not currently implemented in flang.

[Fortran] disable teams-3.f90

---

Fortran/gfortran/regression/DisabledFiles.cmake

Disable a test that declares non-SAVE local variables with allocatable coarray components; this is an error that flang-new will shortly be detecting.

[flang] Disable erroneous test

---

External/HIP/CMakeLists.txt

This easy setup only supports the most recent of Ginkgo. Prior versions have some CMake issue that I did not bother to investigate further.

[HIP] Adds Ginkgo target for version v1.9.0

---

Fortran/gfortran/regression/DisabledFiles.cmake

After the merge of https://github.com/llvm/llvm-project/pull/125115 to flang,  two gfortran tests compile and run successfully after the support of `co_reduce` but they're marked "xfail".

[flang] Disable two xfail tests after co_reduce support

---

utils/compare.py

warning log:
```
./utils/compare.py:206: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
name0 = names[0]
```

[utils] Fix Warning: Series.__getitem__ treating keys as positions  is deprecated

---

External/ffmpeg/CMakeLists.txt
External/ffmpeg/README.md

A new tag has been created on the ffmpeg 7.1 branch now, providing a stable point for us to reference.

[ffmpeg] Reference a tag rather than a branch, for the external source

---

MultiSource/Benchmarks/Prolangs-C/assembler/sym_tab.h
MultiSource/Benchmarks/Prolangs-C/loader/sym_tab.h

Correcting these function declarations addresses these compilation errors:
```
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/loader/sym_tab.c:40:5: error: conflicting types for 'INSERT_IN_SYM_TAB'
40 | int INSERT_IN_SYM_TAB(char *MODULE,char *LABEL,int LOCATION,enum kind TYPE,
|     ^
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/loader/sym_tab.h:52:12: note: previous declaration is here
52 | extern int INSERT_IN_SYM_TAB();
|            ^
1 error generated.
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/assembler/sym_tab.c:40:5: error: conflicting types for 'INSERT_IN_SYM_TAB'
40 | int INSERT_IN_SYM_TAB(char *MODULE,char *LABEL,int LOCATION,enum kind TYPE,
|     ^
llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/assembler/sym_tab.h:52:12: note: previous declaration is here
52 …
```

[Prolangs-C] Fix compilation errors with clang 15 and above

---

Fortran/gfortran/regression/DisabledFiles.cmake

Once LLVM PR https://github.com/llvm/llvm-project/pull/133003 merges, these tests can be enabled.

[flang] Enable FSEEK & FTELL tests

---

Fortran/gfortran/regression/DisabledFiles.cmake

This test calls an empty subroutine with a null pointer as an argument. In gfortran it is hoped that a flag will detect this and produce an error. Flang does not perform any such analysis, and so on some machines when optimization is enabled, this test never terminates. I don't think this is a flang bug as such because the input code is doing undefined behavior.

[Fortran] disable pointer_check_11.f90 which exhibits UB

---

MultiSource/Benchmarks/MallocBench/gs/interp.c

It is undefined behaviour to construct a pointer that is out-of-bounds, not just to use it.
This is a follow-up to commit 9391cd9f62276f019929761d1837791eb53f193e which fixed the same problem (detected by -fsanitize=array-bounds) in MallocBench/cfrac.

Fix UB in MallocBench/gs/interp.c

---

Fortran/gfortran/regression/DisabledFiles.cmake

The tests will start failing at -O2 when I merge
https://github.com/llvm/llvm-project/pull/136071
The HLFIR inlining does not perform the bounds check.

[Fortran/gfortran] Disable bounds-check tests for maxloc.

---

External/SPEC/CINT2006/483.xalancbmk/CMakeLists.txt
External/SPEC/CINT2017rate/523.xalancbmk_r/CMakeLists.txt

-fwrapv-pointer is a relatively recent flag and older versions of clang may not support it.
Hopefully older versions of clang also don't perform the UB optimisation that warrants the use of the flag in the first place

[SPEC] Add compiler check for -fwrapv-pointer in xalancbmk

---

Fortran/gfortran/regression/DisabledFiles.cmake

This test expects the compiler to give a compilation error. Current LLVM flang does emit an error, but it's a TODO message because volatile variables are not handled yet. There are upcoming PRs to enable this though, and the front end ought to emit some diagnostic about this. Eugene E and Peter K are discussing whether these should be warnings or errors. While this is being discussed, disable the test so work on volatile can proceed.
[LLVM PR requiring this change](https://github.com/llvm/llvm-project/pull/132486)
[LLVM issue discussing how to handle this test case](https://github.com/llvm/llvm-project/issues/137369#issuecomment-2831344238)
CC @kiranchandramohan @eugeneepshteyn @vzakhari

[Fortran] Disable gfortran volatile8 test

---

External/SPEC/CINT2017rate/502.gcc_r/CMakeLists.txt
External/SPEC/CINT2017speed/602.gcc_s/CMakeLists.txt

Fixes an ABI-related crash in GCC when running SPEC CPU2017.
See benchmark updates in:
https://www.spec.org/cpu2017/Docs/changes.html

[SPEC2017] Fix known macOS portablitiy issue in GCC

---

Fortran/gfortran/utils/update-test-config.py

Some directories in the gfortran test suite only contain "dependent" sources. These are sources used in multi-file tests where only the "main" source file contains DejaGNU directives that are used to determine the behavior of the test. A list of such "dependents-only" directories have been added to the update-test-config script so a test configuration is not generated for them.

[Fortran/gfortran] Skip some directories when generating test configurations

---

Fortran/gfortran/regression/gomp/DisabledFiles.cmake

This test should fail to compile with an "invalid character in name" error - or the equivalent in flang. However, it used to fail because the LINEAR clause was not implemented in the OpenMP DO construct. The clause is now supported, but flang does not issue the expected compile-time error which causes the test to fail.

[Fortran/gfortran] Disable failing test

---

Fortran/UnitTests/CMakeLists.txt
Fortran/UnitTests/cray_pointers_2/CMakeLists.txt
Fortran/UnitTests/cray_pointers_2/cray_pointers_2.f90
Fortran/UnitTests/cray_pointers_2/lit.local.cfg
Fortran/gfortran/regression/DisabledFiles.cmake

The test started failing after https://github.com/llvm/llvm-project/pull/140803
The issue is that the Cray pointee and the underlying storage
are both accessed in subroutines violating Fortran aliasing rules
for the dummy arguments.
GCC tried to "solve" that by using `-fno-inline` option, but
it should be better to make the aliasing explicit with proper `TARGET`
attribute placement.

[gfortran] Fixed cray_pointers_2.f90 aliasing issues.

---

utils/compare.py

I thought about asserting that all hashes are the same or pick the one with the best metric, but it doesn't seem useful because this property is for internal usage.
This is the only non-numeric column and otherwise an exception is raised:
```Python
Traceback (most recent call last):
File "/home/guyda/.venv/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1824, in apply
result = self._python_apply_general(f, self._selected_obj)
File "/home/guyda/.venv/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1885, in _python_apply_general
values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
File "/home/guyda/.venv/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 919, in apply_groupwise
res = f(group)
File …
```

compare.py: Drop "hash" column for average merging

---

MultiSource/Benchmarks/DOE-ProxyApps-C++/PENNANT/Mesh.cc
MultiSource/Benchmarks/DOE-ProxyApps-C++/miniFE/MatrixInitOp.hpp
SingleSource/UnitTests/Vectorizer/common.h
SingleSource/UnitTests/matrix-types-spec.cpp

When compiling on Fedora 42, there are now test failures in debug mode (c.f. llvm/llvm-project#144678).
This PR fixes the test-failures for all tests but CLAMR where I couldn't figure out what the problem actually is and the code in the upstream repo seems substantially different now.
Most fixes should be fine as is but in `SingleSource/UnitTests/matrix-types-specs.cpp` I changed the type of a matrix to use signed integers instead of unsigned but it seems that these are only transpose tests so it should be fine?
Ping for potential review @nikic @fhahn

Partially fix test failures with libstdc++ 15 in debug mode

---

utils/compare.py

Depending on the distribution, the median can tolerate outliers better than an average to better reflect the central tendency. This change adds a "--merge-median" option to select a median based merge of multiple result files. It also excludes `hash` column merge for median (like avg).

[compare.py] Support median merge function

---

SingleSource/Benchmarks/Misc/Makefile
SingleSource/Benchmarks/Misc/aarch64-init-cpu-features.c

Before this patch, LNT test runs on AArch64 platforms (e.g., macOS arm64) could fail with missing symbol errors:
```
--- Tested: 140 tests --
FAIL: SingleSource/Benchmarks/Misc/aarch64-init-cpu-features.compile_time (1 of 140)
FAIL: SingleSource/Benchmarks/Misc/aarch64-init-cpu-features.execution_time (29 of 140)
Processing Times
```
```
Undefined symbols for architecture arm64:
"_RUNTIME_INIT", referenced from:
_main in aarch64-init-cpu-features.llvm.o
ld: symbol(s) not found for architecture arm64
```
- Selects __init_cpu_features_resolver for Darwin, and __init_cpu_features for Linux.
- Attempts to compile a dummy program to detect availability of the symbol via TARGET_LLVMGCC.
- Adds corresponding macro (HAS_DARWIN_FMV or HAS_LINUX_FMV) if detection succeeds.
- Skips test if the …

[AArch64] Skip test aarch64-init-cpu-features if FMV runtime unavailable.

---

External/SPEC/CFP2017rate/526.blender_r/CMakeLists.txt
External/SPEC/CFP2017rate/544.nab_r/CMakeLists.txt
External/SPEC/CINT2017rate/502.gcc_r/CMakeLists.txt
External/SPEC/CINT2017rate/523.xalancbmk_r/CMakeLists.txt

4 of the SPEC CPU 2017 benchmarks fail to build with the latest GCC, see: https://cc-perf.igalia.com/db_default/v4/nts/31
526.blender_r, 544.nab_r and 502.gcc_r fail because GCC 15 changed the default C standard to gnu23, so this fixes it by telling CMake to use -std=gnu17, which matches Clang's default. I checked and even though CMake doesn't mention gnu17 specifically, it passes -std=gnu17. This is the C version of 7ebe5edc24
523.xalancbmk_r fails for a latent error in a template. We've already had to workaround it in Clang in 92b58b3bf4c6001bff4c7c7f8f98305e3ead56ff but GCC has it's own specific -Wno-error flag to ignore it, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116064

Fix SPEC CPU 2017 benchmarks with GCC 15
